services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order_service:
    build: ./order_service
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672/
      PYTHONUNBUFFERED: "1"
    ports:
      - "8001:8000"
  inventory_service:
    build: ./inventory_service
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672/
      PYTHONUNBUFFERED: "1"
    restart: on-failure
  notification_service:
    build: ./notification_service
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672/
      PYTHONUNBUFFERED: "1"
    restart: on-failure

